#!/bin/sh

timerfile="${XDG_RUNTIME_DIR}/bedstatus-timer"

usage() {
	echo "Usage: timer [-r|-s seconds|-m minutes|-h hours]"
	exit 1
}

update() {
	pkill -USR1 bedstatus
}

args=$(getopt 'as:m:h:r' $*)
[ $? -ne 0 ] && usage

set -- $args

add=0
duration=0

while true; do
	case "$1" in
	-a)
		add=1
		shift
		;;
	-r)
		rm -f "$timerfile"
		update
		exit
		;;
	-s)
		duration=$((duration + $2))
		shift 2
		;;
	-m)
		duration=$((duration + $2 * 60))
		shift 2
		;;
	-h)
		duration=$((duration + $2 * 60 * 60))
		shift 2
		;;
	--)
		shift
		break
		;;
	-*)
		usage
		exit 1
		;;
	esac
done

if [ "$duration" -ne 0 ]; then
	if [ "$add" = 1 ]; then
		old=$(cat "$timerfile")
		timer=$((old + duration))
	else
		now=$(date +%s)
		timer=$((now + duration))
	fi
	echo "$timer" > "$timerfile"
	update
elif [ $# -eq 0 ]; then
	cat "$timerfile"
else
	usage
fi
