#!/bin/ksh
case "$(command -v nvim || command -v vim)" in
*/nvim)		VIM=nvim ;;
*/vim)		VIM=vim	;;
*)		VIM=vi	;;
esac

if command -v colorls; then
	LS=colorls
elif [ "$(uname)" = 'Linux' ]; then
	LS='ls --color=always'
else
	LS=ls
fi

case "$(command -v unzip)" in
*/unzip)	;;
*)		alias unzip='bsdtar -xf' ;;
esac

export EDITOR=$VIM
export FCEDIT=$EDITOR
export PAGER=less
export LC_CTYPE=en_US.UTF-8
export CLICOLOR=1
export TOG_COLORS=1
export CVSROOT=anoncvs@ftp.hostserver.de:/cvs
export AUTOCONF_VERSION=2.72
export AUTOMAKE_VERSION=1.16
HISTFILE=$HOME/.ksh_history
HISTSIZE=20000
RPLAYFLAGS='--cache-secs=10 --stream-buffer-size=1048576'

set -o emacs

alias v="$VIM"
alias t='mkdir -p /tmp/test && cd /tmp/test'
alias ls="$LS -Fh"
alias ll="$LS -Fhl"
alias la="$LS -AFh"
alias lla="$LS -AFhl"
alias dotconfig="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias imgsz="identify -ping -format '%wx%h\\n'"

if [ "$(id -u)" = 0 ]; then
	PS1='\[\033[31m\]\h\[\033[0m\]:\[\033[34m\]\w\[\033[31m\]\$\[\033[0m\] '
else
	PS1='\[\033[32m\]\u@\h\[\033[0m\]:\[\033[34m\]\w\[\033[31m\]\$\[\033[0m\] '
fi

# Completions
if [ -d /var/db/pkg ]; then
	PKG_LIST=$(command ls -1 /var/db/pkg)
	set -A complete_pkg_delete -- ${PKG_LIST}
	set -A complete_pkg_info -- ${PKG_LIST}
fi

#man() {
#	[ ${#complete_man} = 0 ] && {
#		set -A complete_man -- $(command man -k . | grep -o '^[^(]*' | tr ',' '\n' | tr -d ' ' | sort | uniq)
#	}
#	command man "$@"
#}

if [ "$(uname)" = "OpenBSD" ]; then
	set -A complete_rcctl_1 -- configtest check reload restart stop start status disable enable ls
	set -A complete_rcctl_2 -- $(rcctl ls all)
	set -A complete_vmctl_1 -- console create pause reload start status stop unpause wait
	set -A complete_vmctl -- $(vmctl status | awk '!/NAME/{print $NF}')

	export LIBCLANG_PATH="/usr/local/llvm16/lib"
fi

if [ "$(uname)" = "OpenBSD" ] || [ "$(uname)" = "FreeBSD" ]; then
	set -A complete_ifconfig_1 -- $(ifconfig | grep -o '^[a-z0-9]*')
	set -A complete_ifconfig -- up down join nwid wpakey autoconf -inet -inet6
fi

set -A complete_git_1 -- clone init add mv restore rm bisect diff show status branch commit merge rebase reset tag fetch pull push
if command -v got > /dev/null; then
	set -A complete_got_1 -- $(got -h 2>&1 | sed -n 's/commands://p')
fi
COMMANDS=$(command ls -1 -- $(echo "$PATH" | tr ':' '\n') | sort | uniq)
set -A complete_doas_1 -- ${COMMANDS}
set -A complete_which -- ${COMMANDS}
set -A complete_exec -- ${COMMANDS}
set -A complete_pass_1 -- show generate ls edit git rm cp mv
set -A complete_pass -- $(cd $HOME/.password-store && find . -type f -name '*.gpg' | sed 's/^\.\///; s/\.gpg$//')


alias pman='man -M /usr/local/share/doc/posix/man'
alias papropos='apropos -M /usr/local/share/doc/posix/man'
alias pwhatis='whatis -M /usr/local/share/doc/posix/man'
alias tman='man -M /usr/local/lib/tcl/tcl8.6/man'

gd() {
	got di "$@" | bat -l patch
}

gl() {
	got log -d "$@" | bat -l gitlog
}

gls() {
	got log -s "$@" | less
}

_gu_do() {
	got fe -qb "$1"
	got up -qb "origin/$1"
	got rb "$1"
}

gu() {
	if [ $# -gt 1 ]; then
		_gu_old=$(got br)

		for _gu_br in "$@"; do
			_gu_do "${_gu_br}"
		done

		got up -qb "${_gu_old}"
	elif [ $# -eq 1 ]; then
		_gu_do "$1"
	else
		_gu_do "$(got br)"
	fi
	unset _gu_old _gu_br
}

gup() {
	gd > .patch || return 1
	got rv -R .
	gu "$@"
	patch -Np0 < .patch || return 1
}

gua() {
	_gu_old=$(got br)

	got br -l | cut -d: -f1 | sed 's/^[\* ] //' | grep -v '/' | while read -r _gu_br; do
		_gu_do "${_gu_br}"
	done

	got up -qb "${_gu_old}"

	unset _gu_br _gu_old
}

gst() {
	got st "$@" | grep -v '^?'
}

gcl_ls() {
	got st "$@" | sed -n '/^? */s///p'
}

gcl() {
	gcl_ls "$@"
	printf "Remove? "
	read yesno
	[ "$yesno" != 'y' ] && return 1

	gcl_ls "$@" | xargs rm -v 
}

gcli_ls() {
	gcl_ls -I | grep -v '\.vscode'
}

gcli() {
	gcli_ls
	printf "Remove? "
	read yesno
	[ "$yesno" != 'y' ] && return 1

	gcli_ls | xargs rm -v 
}

gse() {
	got se -b "$(got br)" "$@"
}

gbl() {
	got bl "$@" | bat -l c
}

rplay() {
	AUDIODEVICE='snd@192.168.64.7/0' mpv $RPLAYFLAGS "$@"
}

hplay() {
	AUDIODEVICE='snd@192.168.178.59/0' mpv $RPLAYFLAGS "$@"
}

if [ "$TERM" = "xterm" ]; then
	printf '\e[4?h'
fi
