#!/bin/sh

is_muted() {
	case "$(uname)" in
	OpenBSD)
		sndioctl output.mute | cut -d= -f2
		;;
	Linux)
		if [ "$(wpctl get-volume '@DEFAULT_SINK@' | sed -n '/^Volume: .*\[MUTED\]/p')" ]; then
			echo 1
		else
			echo 0
		fi
	esac
}

set_muted() {
	case "$(uname)" in
	OpenBSD)
		sndioctl "output.mute=$1"
		;;
	Linux)
		wpctl set-mute '@DEFAULT_SINK@' "$1"
		;;
	esac
}

get_level() {
	case "$(uname)" in
	OpenBSD)
		sndioctl output.level | cut -d= -f2
		;;
	Linux)
		wpctl get-volume '@DEFAULT_SINK@' | sed -n '/^Volume: /s/^Volume: \([0-9.]*\).*$/\1/p'
		;;
	esac
}

set_level() {
	case "$(uname)" in
	OpenBSD)
		sndioctl "output.level=$1"
		;;
	Linux)
		wpctl set-volume '@DEFAULT_SINK@' "$1"
		;;
	esac
}

while true; do
	muted=$(is_muted)
	level=$(get_level)

	[ "$muted" = 1 ] && m="Unmute" || m="Mute"
	if [ "$muted" = 1 ]; then
		m1=' (Muted)'
		m2='Unmute'
	else
		m1=''
		m2='Mute'
	fi

	p=$(printf 'Level: %.2f%s' "$level" "$m1")
	r=$(printf '%s\n+\n-\n' "$m2" | dmenu -p "$p" -l 5) || break

	case "$r" in
	+)
		set_level "$(printf 'scale=2; %.2f+0.1\n' "$level" | bc)"
		;;
	-)
		set_level "$(printf 'scale=2; %.2f-0.1\n' "$level" | bc)"
		sndioctl "output.level=$level"
		;;
	Mute)
		set_muted 1
		break
		;;
	Unmute)
		set_muted 0
		break
		;;
	*)
		if echo "$r" | grep -qE '^(0|1|0\.[0-9]+)$'; then
			set_level "$r"
			break
		fi
		;;
	esac
done
