#!/bin/sh

while true; do
	muted=$(audioctl is-muted)
	level=$(audioctl get-volume)

	[ "$muted" = 1 ] && m="Unmute" || m="Mute"
	if [ "$muted" = 1 ]; then
		m1=' (Muted)'
		m2='Unmute'
	else
		m1=''
		m2='Mute'
	fi

	p=$(printf 'Level: %.2f%s' "$level" "$m1")
	r=$(printf '%s\n+\n-\n' "$m2" | dmenu -p "$p" -l 5) || break

	case "$r" in
	+)
		audioctl set-volume "$(printf 'scale=2; %.2f+0.1\n' "$level" | bc)"
		;;
	-)
		audioctl set-volume "$(printf 'scale=2; %.2f-0.1\n' "$level" | bc)"
		;;
	Mute)
		audioctl set-muted 1
		break
		;;
	Unmute)
		audioctl set-muted 0
		break
		;;
	*)
		if echo "$r" | grep -qE '^(0|1|0\.[0-9]+)$'; then
			audioctl set-volume "$r"
			break
		fi
		;;
	esac
done
