#!/bin/sh

dir="$HOME/.password-store"
cache="$dir/.cache"

usage() {
	echo "Usage: $0 test|paste|copy|login_enter|login_tab|paste_username|copy_username|test_otp|paste_otp|copy_otp"
	exit 1
}

set_clipboard() {
	echo "$1" | xclip -in -sel primary
	echo "$1" | xclip -in -sel clipboard
}

paste() {
	set_clipboard "$1"
	xdotool key --clearmodifiers 'shift+Insert'
	set_clipboard ""
}

paste_enter() {
	xdotool key Enter
}

paste_tab() {
	xdotool key Tab
}

notify() {
	notify-send			\
		-a 'Password Manager'	\
		-t 2000			\
		'Password Manager'	\
		"$@"
}

# $1 - errmsg
die() {
	printf 'Error: %s\n' "$1" >&2
	notify -u critical "Error: $1"
	exit 1
}

# $1 - comment
# $2 - value
copy() {
	echo "$2" | xclip -in -sel clipboard
	notify "$1 for '$name' copied."
}

list() {
	if [ "$cache" -nt "$dir" ]; then
		cat "$cache"
	elif [ -e "$dir/.gpg-id" ]; then
		cd "$dir"
		find . -type f -name '*.gpg' | sed 's/^\.\/\(.*\)\.gpg/\1/' | sort | tee "$cache"
	else
		die 'Password Store is empty'
	fi
}

mode=$1	# test, paste, copy, login_enter, login_tab

[ -z "$mode" ] && usage

selectpw() {
	name=$(list | dmenu -l 10 -p "$1") || exit 1
}

getuserpass() {
	selectpw "$1"
	creds=$(pass show "$name") || die "Failed to get credentials for '$name'."
	username=$(echo "$creds" | sed -n '/^username: /s///p')
	password=$(echo "$creds" | sed -n '/^password: /s///p')
	{ [ -z "$username" ] || [ -z "$password" ]; } && die "Empty/Invalid credentials for '$name'."
}


getotp() {
	selectpw "$1"
	otp=$(pass otp "$name") || die "Failed to get OTP for '$name'."
}

case "$mode" in
test)
	getuserpass "Test:"
	echo "Username: $username"
	echo "Password: $password"
	;;
paste)
	getuserpass "Password:"
	paste "$password"
	paste_enter
	;;
copy)
	getuserpass "Password:"
	copy "Password" "$password"
	;;
paste_username)
	getuserpass "Username:"
	paste "$username"
	paste_enter
	;;
copy_username)
	getuserpass "Username:"
	copy "Username" "$username"
	;;
login_tab)
	getuserpass "Account:"
	paste "$username"
	paste_tab
	paste "$password"
	paste_tab
	;;
login_enter)
	getuserpass "Account:"
	paste "$username"
	paste_enter
	paste "$password"
	paste_enter
	;;
test_otp)
	getotp "Test (OTP):"
	echo "OTP: $otp"
	;;
paste_otp)
	getotp "OTP:"
	paste "$otp"
	paste_enter
	;;
copy_otp)
	getotp "OTP:"
	copy "OTP" "$otp"
	;;
*)
	usage
	;;
esac
