#!/bin/sh

case "$(printf 'Lock\nSuspend\nShutdown\nReboot\nHibernate\n' | dmenu -l 5 "$@")" in
Lock)
	if pgrep xidle > /dev/null; then
		pkill -USR1 xidle
	else
		slock
	fi
	;;
Suspend)
	case "$(uname)" in
	OpenBSD|FreeBSD)
		doas zzz
		;;
	Linux)
		systemctl suspend
		;;
	esac
Shutdown)
	doas shutdown -p now
	;;
Reboot)
	doas reboot
	;;
Hibernate)
	case "$(uname)" in
	OpenBSD)
		ZZZ
		;;
	Linux)
		systemctl hibernate
		;;
	esac
	;;
esac
