#!/bin/sh

option=$(printf 'Reset keybindings\nRU\nRU-Keymap\n' | dmenu -l 3 -p "X Config") || exit 0

case "$option" in
'Reset keybindings')
	@SCRIPTS@/restore-keybinds
	;;
RU)
	setxkbmap ru
	;;
RU-Keymap)
	nsxiv -N ruskbd -g 800x300+0+0 @DATADIR@/kbd-ru.png &
	;;
esac

