#!/bin/sh

case "$(printf 'Lock\nSuspend\nShutdown\nReboot\nHibernate\n' | dmenu -l 5 "$@")" in
Lock)
	@SCRIPTS@/lock
	;;
Suspend)
	@SCRIPTS@/lock
	case "$(uname)" in
	OpenBSD|FreeBSD)
		doas zzz
		;;
	Linux)
		systemctl suspend
		;;
	esac
	;;
Shutdown)
	case "$(uname)" in
	OpenBSD|FreeBSD)
		doas shutdown -p now
		;;
	Linux)
		doas poweroff
		;;
	esac
	;;
Reboot)
	doas reboot
	;;
Hibernate)
	@SCRIPTS@/lock
	case "$(uname)" in
	OpenBSD)
		ZZZ
		;;
	Linux)
		systemctl hibernate
		;;
	esac
	;;
esac
