#!/bin/sh

choice=$(man -k . | dmenu -l 20 -p "Manual:" "$@" | sed 's/^\([^(]*\)(\([^)]*\)).*$/\2;\1/')
[ -z "$choice" ] && exit 1

section=$(echo "$choice" | cut -d ';' -f2)
page=$(echo "$choice" | cut -d: -f2 | cut -d ';' -f1)

st -- man "$section" "$page"
